spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect